### ISSUE TITLE
Bug in PointSourceReconstruction.py

### ISSUE THREAD

**Issue by cbender98** [IMSY-DKFZ/simpa#184]
- The `PointSourceReconstruction.py` in `simpa_tests/manual_tests/image_reconstruction` is not working.

More precisely you get:
```
Error using kspaceFirstOrder_inputChecking
sensor.mask must be a binary grid with at least one element set to 1.

Error in kspaceFirstOrder2D (line 537)
kspaceFirstOrder_inputChecking;

Error in kspaceFirstOrder3DC (line 532)
eval(run_string);

Error in kspaceFirstOrder2DG (line 76)
sensor_data = kspaceFirstOrder3DC(varargin{:});

Error in simulate_2D (line 157)
    time_series_data = kspaceFirstOrder2DG(kgrid, medium, source, sensor, input_args{:});
 
Traceback (most recent call last):
  File "/home/c738r/simpa/simpa_tests/manual_tests/image_reconstruction/PointSourceReconstruction.py", line 225, in <module>
    dist.append(simulate_and_evaluate_with_device(MSOTAcuityEcho(device_position_mm=np.array([VOLUME_TRANSDUCER_DIM_IN_MM/2,
  File "/home/c738r/simpa/simpa_tests/manual_tests/image_reconstruction/PointSourceReconstruction.py", line 168, in simulate_and_evaluate_with_device
    simulate(SIMUATION_PIPELINE, settings, _device)
  File "/home/c738r/simpa/simpa_venv/lib/python3.8/site-packages/simpa/core/simulation.py", line 81, in simulate
    pipeline_element.run(digital_device_twin)
  File "/home/c738r/simpa/simpa_venv/lib/python3.8/site-packages/simpa/core/simulation_modules/acoustic_forward_module/__init__.py", line 67, in run
    time_series_data = self.forward_model(_device)
  File "/home/c738r/simpa/simpa_venv/lib/python3.8/site-packages/simpa/core/simulation_modules/acoustic_forward_module/acoustic_forward_module_k_wave_adapter.py", line 118, in forward_model
    time_series_data, global_settings = self.k_wave_acoustic_forward_model(
  File "/home/c738r/simpa/simpa_venv/lib/python3.8/site-packages/simpa/core/simulation_modules/acoustic_forward_module/acoustic_forward_module_k_wave_adapter.py", line 255, in k_wave_acoustic_forward_model
    raw_time_series_data = sio.loadmat(optical_path)[Tags.DATA_FIELD_TIME_SERIES_DATA]
KeyError: 'time_series_data'
```

- In addition, the script is not object-oriented like the other manual test scripts. It would be nice to use the same structure as the other scripts (especially for implementing a automatic manual test workflow).

**Comment by TomTomRixRix** [comment]
This tests used to work until this [commit](https://github.com/IMSY-DKFZ/simpa/commit/0286fe971093c62505a8698fa60dcf1d809912c4) 0286fe971093c62505a8698fa60dcf1d809912c4
